### ISSUE TITLE
An2E_2020 sollte ein neuer stand des bisherigen Repos An2E sein

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/An2E_2020#1]
Die Version 2020 der Zusammenfassung des Moduls An2E sollte ein neuer Stand des Repos www.github.com/hsr-stud/An2E sein, kein eigenes Repo. Genau dafür ist die Versionsverwaltung (wie z.B. Git) da.

@pescara @Dev4Future

**Comment by NaoPross** [comment]
Ja makes sense, aber ich habe schon gesehen dass viele Versionen gibt. Wie zB

- https://github.com/HSR-Stud/An2aE_2019
- https://github.com/HSR-Stud/An2bE_2019
- https://github.com/HSR-Stud/An2E_2013
- https://github.com/HSR-Stud/An2E

Ich habe die Namenskonvention von [hier](https://github.com/HSR-Stud/Willkommen#namenskonvention) genommen und sie lautet:

> 1. ModulName: Bei einem Repo von einem Fach von dem es bisher noch keine Zusammenfassung gab
> 2. ModulName_Jahr: Bei einem neuen Repo, wo es schon eine erste Zusammenfassung gab
> 3. Kein neues Repo: Wenn ein bestehendes Repo lediglich leicht abgeändert wurde! WICHTIG: Es soll kein neues Repo erstellt werden, wenn lediglich kleine Änderungen/Verbesserungen gemacht wurden!

**Comment by NaoPross** [comment]
Ich habe die Logik so verstanden, dass weil der Lehrinhalt ändert werden kann, braucht man verschiedene Repos für jeder Semester. Aber ich siehe auch wie ein up to date, easy to find zentrale Repo zu haben nützlich sein kann. zB `An2E` soll immer der derzeitige Zusammenfassung sein

Aber ich finde es nicht so gut, dass man immer der Name ändert (so dass An2E immer zum up-to-date Zusammenfassung zeigt), weil dann die Git Remotes im lokales Repo (auf den eigenen Computer) stimmen nicht mehr.

Und der Namenskonvention braucht noch ein Paar Änderungen / Bessere Durchsetzung, weil es gibt
- https://github.com/HSR-Stud/An2bE_2019
- https://github.com/HSR-Stud/An2bE_2019_1

Sowie
- https://github.com/HSR-Stud/VWL_FS18
- https://github.com/HSR-Stud/Geotech217
- https://github.com/HSR-Stud/PmSwEng-Zusammenfassung
- usw.

Ich würde eher vorschlagen, dass wir das zentrale Repo von An2E nutzen, um Links (oder git-Submodule) zu den verschiedenen Repositorien für jedes Jahr/Semester zu haben.

Oder wir könnten ein weiteres zentrales Management-Repo mit einer umfassenden Liste von Zusammenfassungen haben, bei dem die Leute Pull-Request / Issues einreichen könnten, um neue Repositorien hinzuzufügen. zB ein md File im [Wikommen Repo](https://github.com/HSR-Stud/Willkommen) ?
